import { Quest, Book, Language } from './types';

export const QUESTS: Record<string, Quest> = {
  first_contact: {
    id: 'first_contact',
    name: 'Первый контакт',
    name_kk: 'Алғашқы байланыс',
    name_en: 'First Contact',
    desc: 'Задай свой первый вопрос ИИ-репетитору',
    desc_kk: 'ЖИ-репетиторға алғашқы сұрауды жібер',
    desc_en: 'Ask your first question to the AI tutor',
    xp: 20,
    reward: 'Бейдж Новичок',
    reward_kk: 'Новичок бейджі',
    reward_en: 'Novice Badge',
  },
  material_scout: {
    id: 'material_scout',
    name: 'Поиск материала',
    name_kk: 'Материал іздеу',
    name_en: 'Material Scout',
    desc: 'Используй модуль MaterialSwap для подбора материалов',
    desc_kk: 'MaterialSwap модулін қолданып материал таңда',
    desc_en: 'Use the MaterialSwap module for selection',
    xp: 30,
    reward: 'Бейдж Исследователь',
    reward_kk: 'Зерттеуші бейджі',
    reward_en: 'Explorer Badge',
  },
  streak_master: {
    id: 'streak_master',
    name: 'Серия побед',
    name_kk: 'Жеңіс сериясы',
    name_en: 'Streak Master',
    desc: 'Заходи 3 дня подряд и решай инженерные задачи',
    desc_kk: '3 күн қатарынан кіріп тапсырма орында',
    desc_en: 'Maintain a 3-day active engineering streak',
    xp: 50,
    reward: 'Бейдж Постоянец',
    reward_kk: 'Тұрақты қатысушы бейджі',
    reward_en: 'Regular Badge',
  },
  xp_hunter: {
    id: 'xp_hunter',
    name: 'Охотник за XP',
    name_kk: 'XP аңшысы',
    name_en: 'XP Hunter',
    desc: 'Набери 100 XP за выполнение инженерных модулей',
    desc_kk: '100 XP жина',
    desc_en: 'Earn 100 XP across engineering activities',
    xp: 40,
    reward: 'Бейдж Опытный',
    reward_kk: 'Тәжірибелі бейджі',
    reward_en: 'Experienced Badge',
  },
  module_explorer: {
    id: 'module_explorer',
    name: 'Инженер-универсал',
    name_kk: 'Модуль зерттеушісі',
    name_en: 'Module Explorer',
    desc: 'Используй все 5 модулей (TUTOR, MaterialSwap, PatentCraft, EngiLegal, EngiMatch)',
    desc_kk: 'Барлық 5 модульді қолданып көр',
    desc_en: 'Try all 5 engineering modules',
    xp: 100,
    reward: 'Бейдж Универсал',
    reward_kk: 'Универсал бейджі',
    reward_en: 'Universal Badge',
  },
};

export const BOOKS: Book[] = [
  {
    id: 'mech-1',
    title: 'Сопротивление материалов (Сопромат)',
    category: 'mechanical',
    lang: 'ru',
    author: 'Проф. Феодосьев В.И.',
    pages: 544,
    description: 'Расчеты балок, ферм, кручения и растяжения для инженерных конструкций.',
    sourceUrl: 'https://books.google.com/books?id=KTwrAAAAIAAJ',
  },
  {
    id: 'mech-2',
    title: 'Mechanical Engineering Design',
    category: 'mechanical',
    lang: 'en',
    author: 'Shigley R.',
    pages: 1030,
    description: 'Standard textbook on machine components, stress analysis, and fatigue failure.',
    sourceUrl: 'https://books.google.com/books?id=A2mjQR6Nwn4C',
  },
  {
    id: 'mech-3',
    title: 'Материалдар кедергісі',
    category: 'mechanical',
    lang: 'kz',
    author: 'Жүнісбеков С., Іргебаев Т.І.',
    pages: 266,
    description: 'Қазақ тіліндегі инженерлік материалдар мен конструкциялар беріктігі.',
    sourceUrl: 'https://darynbaspa.kz/kz/shop/materialdar-kedergisi-o%D2%9Buly%D2%9B',
  },
  {
    id: 'elec-1',
    title: 'Теоретические основы электротехники (ТОЭ)',
    category: 'electrical',
    lang: 'ru',
    author: 'Бессонов Л.А.',
    pages: 680,
    description: 'Анализ электрических и магнитных цепей, переходные процессы.',
    sourceUrl: 'https://books.google.com/books?q=%D0%91%D0%B5%D1%81%D1%81%D0%BE%D0%BD%D0%BE%D0%B2+%D0%A2%D0%B5%D0%BE%D1%80%D0%B5%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5+%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%8B+%D1%8D%D0%BB%D0%B5%D0%BA%D1%82%D1%80%D0%BE%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D0%BA%D0%B8',
  },
  {
    id: 'elec-2',
    title: 'Practical Electronics for Inventors',
    category: 'electrical',
    lang: 'en',
    author: 'Scherz P., Monk S.',
    pages: 1072,
    description: 'Comprehensive guide to microcontrollers, sensors, power systems, and circuits.',
    sourceUrl: 'https://books.google.com/books?id=lhSCCwAAQBAJ',
  },
  {
    id: 'rob-1',
    title: 'Основы робототехники',
    category: 'robotics',
    lang: 'ru',
    author: 'Юревич Е.И.',
    pages: 304,
    description: 'Устройство, управление, проектирование и промышленное применение робототехнических систем.',
    sourceUrl: 'https://books.google.com/books?id=uFFLDwAAQBAJ',
  },
  {
    id: 'rob-2',
    title: 'Modern Robotics: Mechanics & Control',
    category: 'robotics',
    lang: 'en',
    author: 'Lynch K., Park F.',
    pages: 520,
    description: 'Rigorous mathematical introduction to kinematics, dynamics, and trajectory motion.',
    sourceUrl: 'https://modernrobotics.northwestern.edu/nu-gm-book-resource/',
  },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  ru: {
    logoTitle: 'ENGINEERUS Quest',
    heroTag: 'Рабочее пространство студента-инженера',
    heroDesc: 'Разбирайте инженерные задачи, фиксируйте прогресс и собирайте учебные проекты в одном месте.',
    startLearning: 'Начать обучение',
    loginBtn: 'Войти',
    registerBtn: 'Регистрация',
    navHome: 'Главная',
    navQuests: 'Квесты',
    navLeaderboard: 'Таблица лидеров',
    navAI: 'ИИ-Помощник',
    navRoadmap: 'Обучение & Книги',
    xpLabel: 'XP Очки',
    levelLabel: 'Уровень',
    streakLabel: 'Дней подряд',
    questsDoneLabel: 'Квестов выполнено',
    nextLevelLabel: 'До следующего уровня',
    activeQuestsTitle: 'Активные инженерные квесты',
    claimReward: 'Выполнить квест',
    questCompleted: 'Квест выполнен! ✓',
    leaderboardTitle: 'Таблица лидеров инженеров Казахстана',
    aiAssistantTitle: 'Инженерный ИИ',
    aiAssistantDesc: 'Расчёты, объяснения и инженерные задачи',
    selectModule: 'Выберите модуль:',
    yourQuestion: 'Ваш вопрос или задача:',
    sendQuery: 'Отправить ИИ',
    quickPresets: 'Быстрые примеры задач:',
    roadmapTitle: 'Инженерный путь: 5 шагов к мастерству',
    step1Title: '1. Основы',
    step1Desc: 'Высшая математика, физика, инженерная графика (AutoCAD/CAD)',
    step2Title: '2. Сопромат & Термех',
    step2Desc: 'Расчет балок, эпюры, прочность и устойчивость конструкций',
    step3Title: '3. Термодинамика & Глоссарий',
    step3Desc: 'Теплообмен, гидрогазодинамика, энергоустановки',
    step4Title: '4. Робототехника & Автоматика',
    step4Desc: 'Микроконтроллеры, PLC, датчики, мехатроника',
    step5Title: '5. Дипломный Проект & Патент',
    step5Desc: 'Разработка готового инженерного продукта и подача патента',
    libraryTitle: 'Инженерная библиотека учебников',
    filterAll: 'Все языки',
    filterRu: 'Русский',
    filterEn: 'English',
    filterKz: 'Қазақша',
    attributionCaption: 'Создано при поддержке tg: @Rixxman',
    foundedBy: 'Основатель: @Noob1Minecraft',
    badgesTitle: 'Бейджи и достижения',
    unlockedCount: 'открыто',
    unlockedStatus: 'Разблокировано',
    lockedStatus: 'Заблокировано',
    achievementProgress: 'Прогресс достижения',
    goToComplete: 'Перейти к выполнению',
    daysUnit: 'Дней',
    topEngineers: 'Топ Студентов-Инженеров',
    leaderboardDesc: 'Студенты вузов Казахстана соревнуются за звание лучшего инженера, решая задачи и выполняя квесты!',
    yourPosition: 'Твоя позиция',
    inKazakhstan: 'в Казахстане',
    champion: 'Чемпион',
    you: 'Ты',
    yourAccount: 'Твой аккаунт',
    completedOf: 'из',
    rewardLabel: 'Награда',
    questActionRequired: 'Квест требует выполнения действия:',
    aiCoreTitle: 'Инженерный ИИ',
    engineeringChat: 'Чат',
    savedSolutions: 'Сохранённое',
    newChat: 'Новый чат',
    chatsCount: 'Чаты',
    aiModuleNavLabel: 'Инженерные модули',
    aiExamples: 'Примеры',
    aiEmptyTitle: 'С чего начнём?',
    aiEmptyBody: 'Задайте инженерный вопрос или выберите пример.',
    aiComposerPlaceholder: 'Задайте инженерный вопрос…',
    aiComposerLabel: 'Сообщение инженерному ИИ',
    aiSend: 'Отправить',
    aiSavedChatsLabel: 'Сохранённые чаты',
    aiCloseHistory: 'Закрыть историю чатов',
    fullscreen: 'На весь экран',
    exitFullscreen: 'Выйти из полноэкранного режима',
    aiExampleTutorBeam: 'Эпюра моментов балки',
    aiExampleTutorCarnot: 'Теорема Карно',
    aiExampleTutorMotion: 'Кинематика и динамика',
    aiExampleMaterialSteel: 'Сталь 09Г2С и Сталь 45',
    aiExampleMaterialUav: 'Сплав для корпуса БПЛА',
    aiExampleMaterialWind: 'Композиты для ветроэнергетики',
    aiExamplePatentBridge: 'Мониторинг мостов',
    aiExamplePatentClearance: 'Патентная чистота разработки',
    aiExamplePatentWater: 'Система очистки воды',
    aiExampleLegalSeismic: 'Сейсмостойкость зданий',
    aiExampleLegalContract: 'Риски договора подряда',
    aiExampleLegalPump: 'Сертификация промышленного насоса',
    aiExampleMatchRoles: 'Роли в агро-робототехнике',
    aiExampleMatchEquity: 'Доли инженеров-сооснователей',
    aiExampleMatchEmbedded: 'Специалист по Embedded и ROS2',
    aiSearchSaved: 'Поиск в сохранённом…',
    aiSavedEmptyTitle: 'Нет сохранённых решений',
    aiSavedNoMatches: 'Ничего не найдено',
    aiSavedEmptyBody: 'Сохраняйте полезные ответы из чата, чтобы вернуться к ним позже.',
    aiSavedNoMatchesBody: 'Измените запрос или фильтр.',
    aiAskQuestion: 'Задать вопрос',
    aiCopyAnswer: 'Копировать ответ',
    aiDownloadAnswer: 'Скачать ответ',
    aiDeleteSaved: 'Удалить из сохранённого',
    aiQuestionLabel: 'Вопрос',
    engineeringQuests: 'Инженерные Квесты',
    tutorModuleTitle: 'TUTOR AI & Модули',
    tutorModuleDesc: 'Разберите расчёт, сравните материалы или подготовьте основу технического документа.',
    questsModuleTitle: 'Квесты & XP Система',
    questsModuleDesc: 'Продвигайтесь по учебному маршруту и отмечайте выполненную инженерную практику.',
    progressModuleTitle: 'Прогресс аккаунта',
    progressModuleDesc: 'Прогресс автоматически сохраняется в вашем аккаунте Engineerus.',
    roadmapSubDesc: 'Пошаговая методология подготовки квалифицированных инженеров для рынка Казахстана.',
    librarySubDesc: 'Проверенные академические учебники по Сопромату, Электротехнике и Робототехнике.',
    historyAI: 'История ИИ-Запросов',
    loginTitle: 'Войди в свой профиль',
    registerTitle: 'Создай аккаунт инженера',
    usernameLabel: 'Имя / Никнейм',
  },
  kk: {
    logoTitle: 'ENGINEERUS Quest',
    heroTag: 'Инженер-студенттің жұмыс кеңістігі',
    heroDesc: 'Инженерлік есептерді талдаңыз, ілгерілеуді белгілеңіз және оқу жобаларын бір жерде жинаңыз.',
    startLearning: 'Оқуды бастау',
    loginBtn: 'Кіру',
    registerBtn: 'Тіркелу',
    navHome: 'Басты бет',
    navQuests: 'Квесттер',
    navLeaderboard: 'Көшбасшылар',
    navAI: 'ЖИ-Көмекші',
    navRoadmap: 'Оқыту & Кітаптар',
    xpLabel: 'XP Ұпайлар',
    levelLabel: 'Деңгей',
    streakLabel: 'Қатар келген күн',
    questsDoneLabel: 'Орындалған квесттер',
    nextLevelLabel: 'Келесі деңгейге дейін',
    activeQuestsTitle: 'Белсенді инженерлік квесттер',
    claimReward: 'Квестті тапсыру',
    questCompleted: 'Квест орындалды! ✓',
    leaderboardTitle: 'Қазақстан инженерлерінің рейтингі',
    aiAssistantTitle: 'Инженерлік ЖИ',
    aiAssistantDesc: 'Есептеулер, түсіндірмелер және инженерлік міндеттер',
    selectModule: 'Модульді таңдаңыз:',
    yourQuestion: 'Сұрағыңыз немесе есебіңіз:',
    sendQuery: 'ЖИ-ге жіберу',
    quickPresets: 'Жылдам сұрақ үлгілері:',
    roadmapTitle: 'Инженерлік жол: шеберлікке 5 қадам',
    step1Title: '1. Негіздер',
    step1Desc: 'Жоғары математика, физика, сызба графикасы (AutoCAD)',
    step2Title: '2. Сопромат & Термех',
    step2Desc: 'Беріктік есептеулері, арқалықтар, конструкция орнықтылығы',
    step3Title: '3. Термодинамика',
    step3Desc: 'Жылу алмасу, гидрогаздинамика, энергетика',
    step4Title: '4. Робототехника',
    step4Desc: 'Микроконтроллерлер, PLC, сенсорлар, мехатроника',
    step5Title: '5. Дипломдық жоба',
    step5Desc: 'Инженерлік стартап және Казпатентке өтінім беру',
    libraryTitle: 'Инженерлік кітапхана',
    filterAll: 'Барлық тілдер',
    filterRu: 'Орысша',
    filterEn: 'Ағылшынша',
    filterKz: 'Қазақша',
    attributionCaption: 'tg: @Rixxman қн',
    foundedBy: 'Негізін қалаған: @Noob1Minecraft',
    badgesTitle: 'Бейдждер мен жетістіктер',
    unlockedCount: 'ашылды',
    unlockedStatus: 'Қолжетімді',
    lockedStatus: 'Құлыпталған',
    achievementProgress: 'Жетістік прогресі',
    goToComplete: 'Орындауға өту',
    daysUnit: 'Күн',
    topEngineers: 'Үздік Студент-Инженерлер',
    leaderboardDesc: 'Қазақстан жоғары оқу орындарының студенттері есептерді шығарып, квесттерді орындау арқылы жарысады!',
    yourPosition: 'Сіздің орныңыз',
    inKazakhstan: 'Қазақстанда',
    champion: 'Чемпион',
    you: 'Сіз',
    yourAccount: 'Сіздің аккаунтыңыз',
    completedOf: '/',
    rewardLabel: 'Сыйлық',
    questActionRequired: 'Квест әрекетті орындауды талап етеді:',
    aiCoreTitle: 'Инженерлік ЖИ',
    engineeringChat: 'Чат',
    savedSolutions: 'Сақталғандар',
    newChat: 'Жаңа чат',
    chatsCount: 'Чаттар',
    aiModuleNavLabel: 'Инженерлік модульдер',
    aiExamples: 'Мысалдар',
    aiEmptyTitle: 'Неден бастаймыз?',
    aiEmptyBody: 'Инженерлік сұрақ қойыңыз немесе мысалды таңдаңыз.',
    aiComposerPlaceholder: 'Инженерлік сұрақ қойыңыз…',
    aiComposerLabel: 'Инженерлік ЖИ-ге хабарлама',
    aiSend: 'Жіберу',
    aiSavedChatsLabel: 'Сақталған чаттар',
    aiCloseHistory: 'Чаттар тарихын жабу',
    fullscreen: 'Толық экран',
    exitFullscreen: 'Толық экраннан шығу',
    aiExampleTutorBeam: 'Арқалық моменттерінің эпюрасы',
    aiExampleTutorCarnot: 'Карно теоремасы',
    aiExampleTutorMotion: 'Кинематика және динамика',
    aiExampleMaterialSteel: '09Г2С және Болат 45',
    aiExampleMaterialUav: 'ҰҰА корпусына арналған қорытпа',
    aiExampleMaterialWind: 'Жел энергетикасының композиттері',
    aiExamplePatentBridge: 'Көпірлерді мониторингтеу',
    aiExamplePatentClearance: 'Әзірлеменің патенттік тазалығы',
    aiExamplePatentWater: 'Су тазарту жүйесі',
    aiExampleLegalSeismic: 'Ғимараттардың сейсмотөзімділігі',
    aiExampleLegalContract: 'Мердігерлік шарт тәуекелдері',
    aiExampleLegalPump: 'Өнеркәсіптік сорғыны сертификаттау',
    aiExampleMatchRoles: 'Агро-робототехникадағы рөлдер',
    aiExampleMatchEquity: 'Инженер-негізін қалаушылар үлесі',
    aiExampleMatchEmbedded: 'Embedded және ROS2 маманы',
    aiSearchSaved: 'Сақталғандардан іздеу…',
    aiSavedEmptyTitle: 'Сақталған шешімдер жоқ',
    aiSavedNoMatches: 'Ештеңе табылмады',
    aiSavedEmptyBody: 'Пайдалы жауаптарды кейін оралу үшін чаттан сақтаңыз.',
    aiSavedNoMatchesBody: 'Сұрауды немесе сүзгіні өзгертіңіз.',
    aiAskQuestion: 'Сұрақ қою',
    aiCopyAnswer: 'Жауапты көшіру',
    aiDownloadAnswer: 'Жауапты жүктеу',
    aiDeleteSaved: 'Сақталғандардан жою',
    aiQuestionLabel: 'Сұрақ',
    engineeringQuests: 'Инженерлік Квесттер',
    tutorModuleTitle: 'TUTOR AI & Модульдер',
    tutorModuleDesc: 'Есепті талдаңыз, материалдарды салыстырыңыз немесе техникалық құжаттың негізін дайындаңыз.',
    questsModuleTitle: 'Квесттер & XP Жүйесі',
    questsModuleDesc: 'Оқу бағытымен ілгерілеп, орындалған инженерлік практиканы белгілеңіз.',
    progressModuleTitle: 'Аккаунт прогресі',
    progressModuleDesc: 'Прогресс Engineerus аккаунтыңызда автоматты түрде сақталады.',
    roadmapSubDesc: 'Қазақстан нарығы үшін білікті инженерлерді дайындаудың кезең-кезеңімен методологиясы.',
    librarySubDesc: 'Сопромат, Электротехника және Робототехника бойынша тексерілген академиялық оқулықтар.',
    historyAI: 'ЖИ-Сұраулар тарихы',
    loginTitle: 'Профильге кіру',
    registerTitle: 'Инженер аккаунтын құру',
    usernameLabel: 'Аты-жөні / Никнейм',
  },
  en: {
    logoTitle: 'ENGINEERUS Quest',
    heroTag: 'A workspace for engineering students',
    heroDesc: 'Work through engineering problems, track progress, and keep learning projects in one place.',
    startLearning: 'Start Learning',
    loginBtn: 'Login',
    registerBtn: 'Register',
    navHome: 'Dashboard',
    navQuests: 'Quests',
    navLeaderboard: 'Leaderboard',
    navAI: 'AI Tutor',
    navRoadmap: 'Roadmap & Books',
    xpLabel: 'XP Points',
    levelLabel: 'Level',
    streakLabel: 'Day Streak',
    questsDoneLabel: 'Quests Completed',
    nextLevelLabel: 'Progress to next level',
    activeQuestsTitle: 'Active Engineering Quests',
    claimReward: 'Complete Quest',
    questCompleted: 'Quest Completed! ✓',
    leaderboardTitle: 'Kazakhstan Engineering Leaderboard',
    aiAssistantTitle: 'Engineering AI',
    aiAssistantDesc: 'Calculations, explanations and engineering tasks',
    selectModule: 'Select Module:',
    yourQuestion: 'Your Engineering Prompt / Task:',
    sendQuery: 'Ask AI Tutor',
    quickPresets: 'Quick Preset Prompts:',
    roadmapTitle: "Engineer's Path: 5 Steps to Mastery",
    step1Title: '1. Foundations',
    step1Desc: 'Calculus, Physics, Engineering Graphics & CAD',
    step2Title: '2. Mechanics & Materials',
    step2Desc: 'Stress/strain analysis, beam bending, structural stability',
    step3Title: '3. Thermodynamics & Fluids',
    step3Desc: 'Heat transfer, fluid mechanics, power cycles',
    step4Title: '4. Robotics & Automation',
    step4Desc: 'Microcontrollers, PLCs, Mechatronics & Control Systems',
    step5Title: '5. Capstone Project & Patent',
    step5Desc: 'Build prototype and draft patent filing for NIIP KZ',
    libraryTitle: 'Engineering Textbook Library',
    filterAll: 'All Languages',
    filterRu: 'Russian',
    filterEn: 'English',
    filterKz: 'Kazakh',
    attributionCaption: 'Created with support from tg: @Rixxman',
    foundedBy: 'Founded by: @Noob1Minecraft',
    badgesTitle: 'Badges & Achievements',
    unlockedCount: 'unlocked',
    unlockedStatus: 'Unlocked',
    lockedStatus: 'Locked',
    achievementProgress: 'Achievement Progress',
    goToComplete: 'Go to Complete',
    daysUnit: 'Days',
    topEngineers: 'Top Engineering Students',
    leaderboardDesc: 'Kazakhstan university students compete for the title of top engineer by solving problems and completing quests!',
    yourPosition: 'Your Position',
    inKazakhstan: 'in Kazakhstan',
    champion: 'Champion',
    you: 'You',
    yourAccount: 'Your Account',
    completedOf: 'of',
    rewardLabel: 'Reward',
    questActionRequired: 'Quest requires completing an action:',
    aiCoreTitle: 'Engineering AI Core',
    engineeringChat: 'Chat',
    savedSolutions: 'Saved',
    newChat: 'New Chat',
    chatsCount: 'Chats',
    aiModuleNavLabel: 'Engineering modules',
    aiExamples: 'Examples',
    aiEmptyTitle: 'Where should we start?',
    aiEmptyBody: 'Ask an engineering question or choose an example.',
    aiComposerPlaceholder: 'Ask an engineering question…',
    aiComposerLabel: 'Message Engineering AI',
    aiSend: 'Send',
    aiSavedChatsLabel: 'Saved chats',
    aiCloseHistory: 'Close chat history',
    fullscreen: 'Enter full screen',
    exitFullscreen: 'Exit full screen',
    aiExampleTutorBeam: 'Beam moment diagram',
    aiExampleTutorCarnot: 'Carnot theorem',
    aiExampleTutorMotion: 'Kinematics vs dynamics',
    aiExampleMaterialSteel: '09G2S vs Steel 45',
    aiExampleMaterialUav: 'Alloy for a UAV frame',
    aiExampleMaterialWind: 'Wind-energy composites',
    aiExamplePatentBridge: 'Bridge monitoring device',
    aiExamplePatentClearance: 'Patent clearance review',
    aiExamplePatentWater: 'Water filtration system',
    aiExampleLegalSeismic: 'Building seismic resistance',
    aiExampleLegalContract: 'Engineering contract risks',
    aiExampleLegalPump: 'Industrial pump certification',
    aiExampleMatchRoles: 'Agritech robotics roles',
    aiExampleMatchEquity: 'Engineering founder equity',
    aiExampleMatchEmbedded: 'Embedded and ROS2 specialist',
    aiSearchSaved: 'Search saved…',
    aiSavedEmptyTitle: 'No saved solutions',
    aiSavedNoMatches: 'No matches found',
    aiSavedEmptyBody: 'Save useful chat answers to return to them later.',
    aiSavedNoMatchesBody: 'Change the search or filter.',
    aiAskQuestion: 'Ask a question',
    aiCopyAnswer: 'Copy answer',
    aiDownloadAnswer: 'Download answer',
    aiDeleteSaved: 'Remove from saved',
    aiQuestionLabel: 'Question',
    engineeringQuests: 'Engineering Quests',
    tutorModuleTitle: 'TUTOR AI & Modules',
    tutorModuleDesc: 'Work through a calculation, compare materials, or prepare a technical-document outline.',
    questsModuleTitle: 'Quests & XP System',
    questsModuleDesc: 'Move through a learning path and record completed engineering practice.',
    progressModuleTitle: 'Account progress',
    progressModuleDesc: 'Progress is saved automatically to your Engineerus account.',
    roadmapSubDesc: 'Step-by-step methodology for preparing qualified engineers in Kazakhstan.',
    librarySubDesc: 'Verified academic textbooks on Mechanics, Electrical Engineering, and Robotics.',
    historyAI: 'AI Request History',
    loginTitle: 'Log into your account',
    registerTitle: 'Create Engineer Account',
    usernameLabel: 'Name / Username',
  },
};
