import { Quest, Book, Language } from './types';

export const QUESTS: Record<string, Quest> = {
  first_contact: {
    id: 'first_contact',
    name: 'Первый контакт',
    name_kk: 'Алғашқы байланыс',
    name_en: 'First Contact',
    desc: 'Задай свой первый вопрос ИИ-репетитору',
    desc_kk: 'ЖИ-репетиторға алғашқы сұрауды жібер',
    desc_en: 'Ask your first question to the AI tutor',
    xp: 20,
    reward: 'Бейдж Новичок',
    reward_kk: 'Новичок бейджі',
    reward_en: 'Novice Badge',
  },
  material_scout: {
    id: 'material_scout',
    name: 'Поиск материала',
    name_kk: 'Материал іздеу',
    name_en: 'Material Scout',
    desc: 'Используй модуль MaterialSwap для подбора материалов',
    desc_kk: 'MaterialSwap модулін қолданып материал таңда',
    desc_en: 'Use the MaterialSwap module for selection',
    xp: 30,
    reward: 'Бейдж Исследователь',
    reward_kk: 'Зерттеуші бейджі',
    reward_en: 'Explorer Badge',
  },
  streak_master: {
    id: 'streak_master',
    name: 'Серия побед',
    name_kk: 'Жеңіс сериясы',
    name_en: 'Streak Master',
    desc: 'Заходи 3 дня подряд и решай инженерные задачи',
    desc_kk: '3 күн қатарынан кіріп тапсырма орында',
    desc_en: 'Maintain a 3-day active engineering streak',
    xp: 50,
    reward: 'Бейдж Постоянец',
    reward_kk: 'Тұрақты қатысушы бейджі',
    reward_en: 'Regular Badge',
  },
  xp_hunter: {
    id: 'xp_hunter',
    name: 'Охотник за XP',
    name_kk: 'XP аңшысы',
    name_en: 'XP Hunter',
    desc: 'Набери 100 XP за выполнение инженерных модулей',
    desc_kk: '100 XP жина',
    desc_en: 'Earn 100 XP across engineering activities',
    xp: 40,
    reward: 'Бейдж Опытный',
    reward_kk: 'Тәжірибелі бейджі',
    reward_en: 'Experienced Badge',
  },
  module_explorer: {
    id: 'module_explorer',
    name: 'Инженер-универсал',
    name_kk: 'Модуль зерттеушісі',
    name_en: 'Module Explorer',
    desc: 'Используй все 5 модулей (TUTOR, MaterialSwap, PatentCraft, EngiLegal, EngiMatch)',
    desc_kk: 'Барлық 5 модульді қолданып көр',
    desc_en: 'Try all 5 engineering modules',
    xp: 100,
    reward: 'Бейдж Универсал',
    reward_kk: 'Универсал бейджі',
    reward_en: 'Universal Badge',
  },
};

export const BOOKS: Book[] = [
  {
    id: 'mech-1',
    title: 'Сопротивление материалов (Сопромат)',
    category: 'mechanical',
    lang: 'ru',
    author: 'Проф. Феодосьев В.И.',
    pages: 540,
    description: 'Расчеты балок, ферм, кручения и растяжения для инженерных конструкций.',
  },
  {
    id: 'mech-2',
    title: 'Mechanical Engineering Design',
    category: 'mechanical',
    lang: 'en',
    author: 'Shigley R.',
    pages: 1080,
    description: 'Standard textbook on machine components, stress analysis, and fatigue failure.',
  },
  {
    id: 'mech-3',
    title: 'Материалдар механикасы мен беріктігі',
    category: 'mechanical',
    lang: 'kz',
    author: 'Ахметов Қ.С.',
    pages: 420,
    description: 'Қазақ тіліндегі инженерлік материалдар мен конструкциялар беріктігі.',
  },
  {
    id: 'elec-1',
    title: 'Теоретические основы электротехники (ТОЭ)',
    category: 'electrical',
    lang: 'ru',
    author: 'Бессонов Л.А.',
    pages: 680,
    description: 'Анализ электрических и магнитных цепей, переходные процессы.',
  },
  {
    id: 'elec-2',
    title: 'Practical Electronics for Inventors',
    category: 'electrical',
    lang: 'en',
    author: 'Scherz P., Monk S.',
    pages: 1050,
    description: 'Comprehensive guide to microcontrollers, sensors, power systems, and circuits.',
  },
  {
    id: 'rob-1',
    title: 'Робототехника и автоматика в промышленности',
    category: 'robotics',
    lang: 'ru',
    author: 'Юревич Е.И.',
    pages: 360,
    description: 'Сервоприводы, контроллеры PLC, ROS2 и Кинематика манипуляторов.',
  },
  {
    id: 'rob-2',
    title: 'Modern Robotics: Mechanics & Control',
    category: 'robotics',
    lang: 'en',
    author: 'Lynch K., Park F.',
    pages: 520,
    description: 'Rigorous mathematical introduction to kinematics, dynamics, and trajectory motion.',
  },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  ru: {
    logoTitle: 'ENGINEERUS Quest',
    heroTag: 'Казахстанская ИИ-платформа для студентов-инженеров',
    heroDesc: 'Выполняй квесты • Зарабатывай XP • Осваивай Сопромат, Робототехнику и Патенты',
    startLearning: 'Начать обучение',
    loginBtn: 'Войти',
    registerBtn: 'Регистрация',
    navHome: 'Главная',
    navQuests: 'Квесты',
    navLeaderboard: 'Таблица лидеров',
    navAI: 'ИИ-Помощник',
    navRoadmap: 'Обучение & Книги',
    navSync: 'Синхронизация Telegram',
    xpLabel: 'XP Очки',
    levelLabel: 'Уровень',
    streakLabel: 'Дней подряд',
    questsDoneLabel: 'Квестов выполнено',
    nextLevelLabel: 'До следующего уровня',
    activeQuestsTitle: 'Активные инженерные квесты',
    claimReward: 'Выполнить квест',
    questCompleted: 'Квест выполнен! ✓',
    leaderboardTitle: 'Таблица лидеров инженеров Казахстана',
    aiAssistantTitle: 'Инженерный ИИ-Помощник',
    selectModule: 'Выберите модуль:',
    yourQuestion: 'Ваш вопрос или задача:',
    sendQuery: 'Отправить ИИ',
    quickPresets: 'Быстрые примеры задач:',
    roadmapTitle: 'Инженерный путь: 5 шагов к мастерству',
    step1Title: '1. Основы',
    step1Desc: 'Высшая математика, физика, инженерная графика (AutoCAD/CAD)',
    step2Title: '2. Сопромат & Термех',
    step2Desc: 'Расчет балок, эпюры, прочность и устойчивость конструкций',
    step3Title: '3. Термодинамика & Глоссарий',
    step3Desc: 'Теплообмен, гидрогазодинамика, энергоустановки',
    step4Title: '4. Робототехника & Автоматика',
    step4Desc: 'Микроконтроллеры, PLC, датчики, мехатроника',
    step5Title: '5. Дипломный Проект & Патент',
    step5Desc: 'Разработка готового инженерного продукта и подача патента',
    libraryTitle: 'Инженерная библиотека учебников',
    filterAll: 'Все языки',
    filterRu: 'Русский',
    filterEn: 'English',
    filterKz: 'Қазақша',
    tgSyncTitle: 'Синхронизация с Telegram-ботом',
    tgSyncDesc: 'Единый прогресс между сайтом и Telegram-ботом:',
    tgStep1Title: 'Шаг 1: Запустите Telegram-бота',
    tgStep1Text: 'Найдите @EngineerusQuest_bot в Telegram и отправьте /start',
    tgStep2Title: 'Шаг 2: Привяжите аккаунт',
    tgStep2Text: 'Отправьте команду: /bind email ваш_пароль',
    tgStep3Title: 'Шаг 3: Авторизуйтесь на сайте',
    tgStep3Text: 'Войдите на сайте с тем же email и паролем — XP и уровни объединятся!',
    attributionCaption: 'Создано при поддержке tg: @Rixxman',
    foundedBy: 'Основатель: @Noob1Minecraft',
    badgesTitle: 'Бейджи и достижения',
    unlockedCount: 'открыто',
    unlockedStatus: 'Разблокировано',
    lockedStatus: 'Заблокировано',
    achievementProgress: 'Прогресс достижения',
    goToComplete: 'Перейти к выполнению',
    daysUnit: 'Дней',
    topEngineers: 'Топ Студентов-Инженеров',
    leaderboardDesc: 'Студенты вузов Казахстана соревнуются за звание лучшего инженера, решая задачи и выполняя квесты!',
    yourPosition: 'Твоя позиция',
    inKazakhstan: 'в Казахстане',
    champion: 'Чемпион',
    you: 'Ты',
    yourAccount: 'Твой аккаунт',
    completedOf: 'из',
    rewardLabel: 'Награда',
    questActionRequired: 'Квест требует выполнения действия:',
    aiCoreTitle: 'Инженерный ИИ',
    engineeringChat: 'Инженерный Чат',
    savedSolutions: 'Сохраненные',
    newChat: 'Новый чат',
    chatsCount: 'Чаты',
    engineeringQuests: 'Инженерные Квесты',
    tutorModuleTitle: 'TUTOR AI & Модули',
    tutorModuleDesc: 'Решай задачи по Сопромату, подбирай материалы по ГОСТ РК и генерируй формулы патентов.',
    questsModuleTitle: 'Квесты & XP Система',
    questsModuleDesc: 'Зарабатывай очки опыта, поддерживай дневной стрик и получай бейджи инженерного мастерства.',
    tgModuleTitle: 'Telegram-Бот Синхронизация',
    tgModuleDesc: 'Привяжи свой Telegram аккаунт с помощью команды /bind для бесшовной синхронизации прогресса.',
    roadmapSubDesc: 'Пошаговая методология подготовки квалифицированных инженеров для рынка Казахстана.',
    librarySubDesc: 'Проверенные академические учебники по Сопромату, Электротехнике и Робототехнике.',
    syncActive: 'Синхронизация активна!',
    syncItemsTitle: 'Что синхронизируется между сайтом и ботом:',
    historyAI: 'История ИИ-Запросов',
    loginTitle: 'Войди в свой профиль',
    registerTitle: 'Создай аккаунт инженера',
    usernameLabel: 'Имя / Никнейм',
  },
  kk: {
    logoTitle: 'ENGINEERUS Quest',
    heroTag: 'Қазақстан инженер-студенттеріне арналған ЖИ-платформасы',
    heroDesc: 'Квесттерді орында • XP ұпай жина • Сопромат, Робототехника және Патенттерді меңгер',
    startLearning: 'Оқуды бастау',
    loginBtn: 'Кіру',
    registerBtn: 'Тіркелу',
    navHome: 'Басты бет',
    navQuests: 'Квесттер',
    navLeaderboard: 'Көшбасшылар',
    navAI: 'ЖИ-Көмекші',
    navRoadmap: 'Оқыту & Кітаптар',
    navSync: 'Telegram Синхрон',
    xpLabel: 'XP Ұпайлар',
    levelLabel: 'Деңгей',
    streakLabel: 'Қатар келген күн',
    questsDoneLabel: 'Орындалған квесттер',
    nextLevelLabel: 'Келесі деңгейге дейін',
    activeQuestsTitle: 'Белсенді инженерлік квесттер',
    claimReward: 'Квестті тапсыру',
    questCompleted: 'Квест орындалды! ✓',
    leaderboardTitle: 'Қазақстан инженерлерінің рейтингі',
    aiAssistantTitle: 'Инженерлік ЖИ-Көмекші',
    selectModule: 'Модульді таңдаңыз:',
    yourQuestion: 'Сұрағыңыз немесе есебіңіз:',
    sendQuery: 'ЖИ-ге жіберу',
    quickPresets: 'Жылдам сұрақ үлгілері:',
    roadmapTitle: 'Инженерлік жол: шеберлікке 5 қадам',
    step1Title: '1. Негіздер',
    step1Desc: 'Жоғары математика, физика, сызба графикасы (AutoCAD)',
    step2Title: '2. Сопромат & Термех',
    step2Desc: 'Беріктік есептеулері, арқалықтар, конструкция орнықтылығы',
    step3Title: '3. Термодинамика',
    step3Desc: 'Жылу алмасу, гидрогаздинамика, энергетика',
    step4Title: '4. Робототехника',
    step4Desc: 'Микроконтроллерлер, PLC, сенсорлар, мехатроника',
    step5Title: '5. Дипломдық жоба',
    step5Desc: 'Инженерлік стартап және Казпатентке өтінім беру',
    libraryTitle: 'Инженерлік кітапхана',
    filterAll: 'Барлық тілдер',
    filterRu: 'Орысша',
    filterEn: 'Ағылшынша',
    filterKz: 'Қазақша',
    tgSyncTitle: 'Telegram-ботпен синхрондау',
    tgSyncDesc: 'Сайт пен Telegram-бот арасындағы бірыңғай прогресс:',
    tgStep1Title: '1-қадам: Telegram-ботты іске қосыңыз',
    tgStep1Text: 'Telegram-да @EngineerusQuest_bot тауып, /start басыңыз',
    tgStep2Title: '2-қадам: Аккаунтты байланыстырыңыз',
    tgStep2Text: 'Пәрменді жіберіңіз: /bind email сіздің_пароліңіз',
    tgStep3Title: '3-қадам: Сайтқа кіріңіз',
    tgStep3Text: 'Сайтқа осы email және парольмен кіріңіз — XP автоматты түрде бірігеді!',
    attributionCaption: 'tg: @Rixxman қн',
    foundedBy: 'Негізін қалаған: @Noob1Minecraft',
    badgesTitle: 'Бейдждер мен жетістіктер',
    unlockedCount: 'ашылды',
    unlockedStatus: 'Қолжетімді',
    lockedStatus: 'Құлыпталған',
    achievementProgress: 'Жетістік прогресі',
    goToComplete: 'Орындауға өту',
    daysUnit: 'Күн',
    topEngineers: 'Үздік Студент-Инженерлер',
    leaderboardDesc: 'Қазақстан жоғары оқу орындарының студенттері есептерді шығарып, квесттерді орындау арқылы жарысады!',
    yourPosition: 'Сіздің орныңыз',
    inKazakhstan: 'Қазақстанда',
    champion: 'Чемпион',
    you: 'Сіз',
    yourAccount: 'Сіздің аккаунтыңыз',
    completedOf: '/',
    rewardLabel: 'Сыйлық',
    questActionRequired: 'Квест әрекетті орындауды талап етеді:',
    aiCoreTitle: 'Инженерлік ЖИ',
    engineeringChat: 'Инженерлік Чат',
    savedSolutions: 'Сақталғандар',
    newChat: 'Жаңа чат',
    chatsCount: 'Чаттар',
    engineeringQuests: 'Инженерлік Квесттер',
    tutorModuleTitle: 'TUTOR AI & Модульдер',
    tutorModuleDesc: 'Сопромат есептерін шығар, ҚР МЕМСТ материалдарын таңда және патент формулаларын жаса.',
    questsModuleTitle: 'Квесттер & XP Жүйесі',
    questsModuleDesc: 'XP ұпайларын жина, күнделікті стрикті сақта және инженерлік шеберлік бейдждерін ал.',
    tgModuleTitle: 'Telegram-Бот Синхрондау',
    tgModuleDesc: 'Прогресті үзіліссіз синхрондау үшін /bind пәрмені арқылы Telegram аккаунтыңызды байланыстырыңыз.',
    roadmapSubDesc: 'Қазақстан нарығы үшін білікті инженерлерді дайындаудың кезең-кезеңімен методологиясы.',
    librarySubDesc: 'Сопромат, Электротехника және Робототехника бойынша тексерілген академиялық оқулықтар.',
    syncActive: 'Синхрондау белсенді!',
    syncItemsTitle: 'Сайт пен бот арасында не синхрондалады:',
    historyAI: 'ЖИ-Сұраулар тарихы',
    loginTitle: 'Профильге кіру',
    registerTitle: 'Инженер аккаунтын құру',
    usernameLabel: 'Аты-жөні / Никнейм',
  },
  en: {
    logoTitle: 'ENGINEERUS Quest',
    heroTag: 'AI Learning Platform for Kazakhstan Engineering Students',
    heroDesc: 'Complete Quests • Earn XP • Master Structural Mechanics, Robotics & Patents',
    startLearning: 'Start Learning',
    loginBtn: 'Login',
    registerBtn: 'Register',
    navHome: 'Dashboard',
    navQuests: 'Quests',
    navLeaderboard: 'Leaderboard',
    navAI: 'AI Tutor',
    navRoadmap: 'Roadmap & Books',
    navSync: 'Telegram Sync',
    xpLabel: 'XP Points',
    levelLabel: 'Level',
    streakLabel: 'Day Streak',
    questsDoneLabel: 'Quests Completed',
    nextLevelLabel: 'Progress to next level',
    activeQuestsTitle: 'Active Engineering Quests',
    claimReward: 'Complete Quest',
    questCompleted: 'Quest Completed! ✓',
    leaderboardTitle: 'Kazakhstan Engineering Leaderboard',
    aiAssistantTitle: 'Engineering AI Assistant',
    selectModule: 'Select Module:',
    yourQuestion: 'Your Engineering Prompt / Task:',
    sendQuery: 'Ask AI Tutor',
    quickPresets: 'Quick Preset Prompts:',
    roadmapTitle: "Engineer's Path: 5 Steps to Mastery",
    step1Title: '1. Foundations',
    step1Desc: 'Calculus, Physics, Engineering Graphics & CAD',
    step2Title: '2. Mechanics & Materials',
    step2Desc: 'Stress/strain analysis, beam bending, structural stability',
    step3Title: '3. Thermodynamics & Fluids',
    step3Desc: 'Heat transfer, fluid mechanics, power cycles',
    step4Title: '4. Robotics & Automation',
    step4Desc: 'Microcontrollers, PLCs, Mechatronics & Control Systems',
    step5Title: '5. Capstone Project & Patent',
    step5Desc: 'Build prototype and draft patent filing for NIIP KZ',
    libraryTitle: 'Engineering Textbook Library',
    filterAll: 'All Languages',
    filterRu: 'Russian',
    filterEn: 'English',
    filterKz: 'Kazakh',
    tgSyncTitle: 'Telegram Bot Sync',
    tgSyncDesc: 'Unified progress sync between website and Telegram bot:',
    tgStep1Title: 'Step 1: Start Telegram Bot',
    tgStep1Text: 'Find @EngineerusQuest_bot in Telegram and send /start',
    tgStep2Title: 'Step 2: Bind Account',
    tgStep2Text: 'Send command: /bind email your_password',
    tgStep3Title: 'Step 3: Log in on Web',
    tgStep3Text: 'Log in with the same email & password — XP and streaks sync instantly!',
    attributionCaption: 'Created with support from tg: @Rixxman',
    foundedBy: 'Founded by: @Noob1Minecraft',
    badgesTitle: 'Badges & Achievements',
    unlockedCount: 'unlocked',
    unlockedStatus: 'Unlocked',
    lockedStatus: 'Locked',
    achievementProgress: 'Achievement Progress',
    goToComplete: 'Go to Complete',
    daysUnit: 'Days',
    topEngineers: 'Top Engineering Students',
    leaderboardDesc: 'Kazakhstan university students compete for the title of top engineer by solving problems and completing quests!',
    yourPosition: 'Your Position',
    inKazakhstan: 'in Kazakhstan',
    champion: 'Champion',
    you: 'You',
    yourAccount: 'Your Account',
    completedOf: 'of',
    rewardLabel: 'Reward',
    questActionRequired: 'Quest requires completing an action:',
    aiCoreTitle: 'Engineering AI Core',
    engineeringChat: 'Engineering Chat',
    savedSolutions: 'Saved Solutions',
    newChat: 'New Chat',
    chatsCount: 'Chats',
    engineeringQuests: 'Engineering Quests',
    tutorModuleTitle: 'TUTOR AI & Modules',
    tutorModuleDesc: 'Solve structural mechanics tasks, match materials by GOST KZ, and generate patent claims.',
    questsModuleTitle: 'Quests & XP System',
    questsModuleDesc: 'Earn XP, maintain daily streaks, and earn engineering mastery badges.',
    tgModuleTitle: 'Telegram Bot Sync',
    tgModuleDesc: 'Link your Telegram account using /bind command for seamless progress sync.',
    roadmapSubDesc: 'Step-by-step methodology for preparing qualified engineers in Kazakhstan.',
    librarySubDesc: 'Verified academic textbooks on Mechanics, Electrical Engineering, and Robotics.',
    syncActive: 'Sync Active!',
    syncItemsTitle: 'What is synchronized between website and bot:',
    historyAI: 'AI Request History',
    loginTitle: 'Log into your account',
    registerTitle: 'Create Engineer Account',
    usernameLabel: 'Name / Username',
  },
};
